### ISSUE TITLE
VMwareFusionDeploy should have an installs item, minimum_os_version

### ISSUE THREAD

**Issue by timsutton** [facebook/Recipes-for-AutoPkg#1]
In the past when I've deployed VMwareFusion with the deployment pkg, I've also added an installs item of VMware Fusion.app, because VMware's included package is simply 1.0 and so Munki doesn't have enough to go on to keep it up to date. Also, it would be good to use the LSMinimumSystemVersion in the app for the pkginfo's minimum_os_version.

Would you consider a pull request that adds these?

Thanks for this recipe!

**Comment by nmcspadden** [comment]
We'd absolutely appreciate a pull request.  Please keep in mind our contribution requirements [here](https://github.com/facebook/Recipes-for-AutoPkg/blob/master/CONTRIBUTING.md).
