### ISSUE TITLE
Xcode names on disk as variable for overrides

### ISSUE THREAD

**Issue by sha512imoto** [facebook/Recipes-for-AutoPkg#13]
It would be most excellent if the names on disk could be a variable that one could employ in an override for the autopkg.

The .munki recipes for Xcode include version and beta numbers in the names on disk.

- `/Applications/%NAME%_%version%.app`
- `/Applications/%NAME%_%version%_beta_%BETA_NUMBER%.app`

Xcode, as if from app store, comes as:

- `/Applications/%NAME%.app`
- `/Applications/%NAME%-beta.app`

Perhaps the name could use new variable like %APP_NAME%.

- `/Applications/%APP_NAME%` where `%APP_NAME% == %NAME%.app`
- `/Applications/%APP_NAME%` where `%APP_NAME% == %NAME%-beta.app`

**Comment by nmcspadden** [comment]
Fixed with 93657872b509fdb2e3fbb069986d3b8915e317af.

You can create two overrides - one for Xcode and one for Xcode-beta, and set the new input variable `DESTINATION_APP_NAME` to whatever you'd like.
