### ISSUE TITLE
Mosh URL has changed 

### ISSUE THREAD

**Issue by mm-johnpeterson** [facebook/Recipes-for-AutoPkg#19]
<key>Processor</key>
            <string>URLTextSearcher</string>
            <key>Arguments</key>
            <dict>
                <key>url</key>
                <string>https://mosh.org/#getting</string>
                <key>re_pattern</key>
                <string>https://mosh.org/mosh-[0-9,.]\..\..\.pkg</string>

URL is https://mosh.mit.edu/#getting on https://github.com/facebook/Recipes-for-AutoPkg/blob/master/Mosh/mosh.download.recipe 
Snippet above has working URL. https://mosh.org/#getting

**Comment by nmcspadden** [comment]
Fixed in 61fa474d2fdb17964080cd22709b6408b4d7adb1
