### ISSUE TITLE
rsync processor cannot be used with a mix of short and long arguements e.g. `-Phav --delete` 

### ISSUE THREAD

**Issue by matt-cahill** [facebook/Recipes-for-AutoPkg#23]
Mixing short and long arguments results in an unrecognised argument error as the whole argument string is sent as one argument. This is mostly fine except if you need to use delete as there is no short argument for delete.

**Comment by nmcspadden** [comment]
Fixed with 988332d3bb700b0e5c4231c16dfe39527c68a9a5.
