### ISSUE TITLE
More suggestions for improving VMwareDeploy

### ISSUE THREAD

**Issue by timsutton** [facebook/Recipes-for-AutoPkg#3]
Some additional possible improvements to the VMwareDeploy Munki recipes, as per discussed in Slack.

- [x] Set `LICENSE_KEY` default override to one that's not commented, or...
- [x] ..alternatively, allow the override to specify a path to a Deploy.ini file, or give its contents _as_ the override value.
- [x] Improve uninstaller logic - the pkg cannot actually be removed using only `remove_packages`. It should be either not uninstallable or have its own uninstall_script.
- [x] Break up packaging and Munki-related logic into two recipes for use by systems other than Munki.

**Comment by nmcspadden** [comment]
These are addressed with the merge from development at commit https://github.com/facebook/Recipes-for-AutoPkg/commit/cbc424e49210a06ea146a8a2c490783945c7e6bf.

**Comment by timsutton** [comment]
Thanks! These recipes should prove very useful to anyone deploying Fusion.
