### ISSUE TITLE
TypeError on Mosh recipe

### ISSUE THREAD

**Issue by mm-johnpeterson** [facebook/Recipes-for-AutoPkg#45]
Fair chance I'm missing something here. Running autopkg 2.0.2

`$ autopkg run -v mosh.munki
Processing mosh.munki...
URLTextSearcher
URLTextSearcher: Found matching text (match): https://mosh.org/mosh-1.3.2.pkg
URLDownloader
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/john/Library/AutoPkg/Cache/local.munki.mosh/downloads/mosh-1.3.2.pkg
MoshVersioner
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 480, in process
    self.main()
  File "/Users/john/Library/AutoPkg/RecipeRepos/com.github.facebook.Recipes-for-AutoPkg/Mosh/MoshVersioner.py", line 56, in main
    self.env["version"] = unfixed.lstrip("mosh-")
TypeError: a bytes-like object is required, not 'str'
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
a bytes-like object is required, not 'str'`

If I print out `unfixed` I get b'mosh-1.3.2' which makes sense after line 54 in MoshVersioner. Since lstrip is looking for a string if I decode `unfixed` with `unfixed = unfixed.decode("utf-8")` before `self.env["version"] = unfixed.lstrip("mosh-")` everything works fine.

**Comment by nmcspadden** [comment]
Fixed in https://github.com/facebook/Recipes-for-AutoPkg/commit/bda86c53175d5464c7c31afea8ca5dd7da707bf9.
