### ISSUE TITLE
Unused variables

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [facebook/Recipes-for-AutoPkg#49]
https://github.com/facebook/Recipes-for-AutoPkg/blob/ef5dee35c65daf15070acd3dd37230f006f9babb/Xcode/XcodeVersioner.py#L66

Variables declared but not used, or reassigned before they are used, can be the result of programmer negligence, which often means that there is a bug in the program.

**Comment by nmcspadden** [comment]
The variable itself is unused and should be marked with an underscore to indicate that, but the action of loading the bundle is necessary to allow access to the frameworks.
