### ISSUE TITLE
IntelliJ update address has changed

### ISSUE THREAD

**Issue by rtrouton** [facebook/Recipes-for-AutoPkg#6]
The JetBrains URL used by the **IntellijURLProvider** AutoPkg processer appears to be no longer updated:

http://www.jetbrains.com/js2/version.js

Reference: https://github.com/facebook/Recipes-for-AutoPkg/blob/master/Intellij/IntellijURLProvider.py#L19

The new update address appears to be the URL below:

http://www.jetbrains.com/updates/updates.xml

Reference: https://github.com/JetBrains/intellij-community/blob/master/community-resources/src/idea/IdeaApplicationInfo.xml#L16

Could the **IntellijURLProvider** processer please be updated to use the new update URL?

**Comment by rtrouton** [comment]
It looks like this issue had been reported to JetBrains in December, with no response at that time:

http://blog.jetbrains.com/blog/2015/12/10/the-drive-to-develop/#comment-243055

**Comment by nmcspadden** [comment]
Fixed with commit https://github.com/facebook/Recipes-for-AutoPkg/commit/41879c9f57d534eb0b1d5cd151075c00cd9fe47b.
