### ISSUE TITLE
Using FileAppender to append variables in .yaml file

### ISSUE THREAD

**Issue by symmtree** [facebook/Recipes-for-AutoPkg#60]
I am trying to populate a .yaml file after Autopkg runs, including some variables from earlier processors in a .download recipe.
Text seems to be fine but variables are only passed along in cleartext.
Am I missing something or is it not possible to pass e.g. %NAME% / %version% variables directly to a .yaml file with this custom processor?
Tried both .recipe and .yaml recipes to pass along variables from with the same result.

**Comment by symmtree** [comment]
FileAppender.

**Comment by nmcspadden** [comment]
This repo will be decommissioned. If this is still an issue, please open it against nmcspadden-recipes.
